// Generates themes/paper.css, the BB theme the manifest contributes
// (`bb.themes`, id "paper"): the Patrick Hand @font-face inlined as a data URL,
// then paper.palette.css. A theme is one CSS file that BB injects app-wide,
// so the font cannot be a separate file. Regenerate: npm run fonts
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { renderFontFaces } from "../fonts/embed.ts";

export const PALETTE_CSS = fileURLToPath(new URL("./paper.palette.css", import.meta.url));
export const THEME_CSS = fileURLToPath(new URL("../../themes/paper.css", import.meta.url));

export function renderThemeCss(): string {
  return [
    "/* Generated by app/theme/build.ts from app/theme/paper.palette.css and app/fonts. Do not edit. */",
    renderFontFaces("Tutor Patrick Hand"),
    "",
    readFileSync(PALETTE_CSS, "utf8"),
  ].join("\n");
}

/** The `--token: value` declarations of the block that starts with `selector {`. */
export function paletteBlock(css: string, selector: string): Record<string, string> {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`no ${JSON.stringify(selector)} block`);
  const end = css.indexOf("}", start);
  const tokens: Record<string, string> = {};
  for (const match of css.slice(start, end).matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    const [, name, value] = match;
    if (name !== undefined && value !== undefined) tokens[name] = value.trim();
  }
  return tokens;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(THEME_CSS, renderThemeCss());
}
