// Generates the BB theme the manifest contributes (`bb.themes`) and its two
// code themes. Regenerate: npm run build:assets
//
// themes/sketchbook.css is the brand's bb theme (vendor/brand, pinned by
// scripts/sync-brand.ts) with three mechanical changes: its Google Fonts
// @import goes, the Patrick Hand @font-face is inlined as a data URL ahead of
// it (a theme is one CSS file, and the app must not fetch fonts at run time),
// and `--font-sans` names that self-hosted face first. Everything else is
// the vendored file, byte for byte; theme.test.ts proves it. A problem in the
// theme is fixed in the brand repo and re-pinned, never patched here.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { renderFontFaces } from "../fonts/embed.ts";
import { BB_BASE_TOKENS } from "./bb-base-tokens.ts";
import { renderCodeTheme } from "./code-theme.ts";
import type { Tokens } from "./color.ts";

const path = (relative: string) => fileURLToPath(new URL(relative, import.meta.url));

export const VENDORED_THEME = path("../../vendor/brand/bb-theme/sketchbook/theme.css");
export const BRAND_PIN = readFileSync(path("../../vendor/brand/PIN"), "utf8").trim();
export const THEME_CSS = path("../../themes/sketchbook.css");
export const CODE_THEME_FILES = {
  light: path("../../themes/sketchbook-code-light.json"),
  dark: path("../../themes/sketchbook-code-dark.json"),
} as const;

/** The theme minus its `@import` lines and the blank lines right after them. */
export function stripImport(css: string): string {
  return css.replace(/^@import [^\n]*\n(?:\n)*/gm, "");
}

const BRAND_FONT = '"Patrick Hand"';
const TUTOR_FONT = '"Tutor Patrick Hand"';

/** Puts the self-hosted face ahead of the brand's first family, keeping the rest of the stack. */
function selfHostFont(css: string): string {
  const declarations = [...css.matchAll(/(--font-sans:\s*)([^;]+);/g)];
  if (declarations.length !== 1) throw new Error(`expected one --font-sans in the brand theme, found ${declarations.length}`);
  const [whole, prefix, value] = declarations[0] as unknown as [string, string, string];
  if (!value.startsWith(`${BRAND_FONT},`)) throw new Error(`the brand theme's --font-sans no longer starts with ${BRAND_FONT}: ${value}`);
  return css.replace(whole, `${prefix}${TUTOR_FONT}, ${value};`);
}

export function renderThemeCss(vendored: string = readFileSync(VENDORED_THEME, "utf8")): string {
  return [
    `/* Generated by app/theme/build.ts from vendor/brand/bb-theme/sketchbook/theme.css (brand ${BRAND_PIN}) and app/fonts. Do not edit. */`,
    renderFontFaces("Tutor Patrick Hand"),
    "",
    selfHostFont(stripImport(vendored)),
  ].join("\n");
}

/** The `--token: value` declarations of the block that starts with `selector {`, comments ignored. */
export function themeBlock(css: string, selector: string): Tokens {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`no ${JSON.stringify(selector)} block`);
  const end = css.indexOf("}", start);
  const tokens: Record<string, string> = {};
  const block = css.slice(start + selector.length + 2, end).replace(/\/\*[\s\S]*?\*\//g, "");
  for (const match of block.matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    const [, name, value] = match;
    if (name !== undefined && value !== undefined) tokens[name] = value.trim();
  }
  return tokens;
}

/**
 * The tokens BB paints with in each mode once the theme is injected: BB's own
 * light values, then its dark ones (dark mode), then the theme's `:root, .light`,
 * then its `.dark` (dark mode). The theme comes last with equal specificity, so
 * its `:root` values beat BB's `.dark` ones too.
 */
export function modeTokens(css: string, mode: "light" | "dark"): Tokens {
  const root = themeBlock(css, ":root,\n.light");
  if (mode === "light") return { ...BB_BASE_TOKENS.light, ...root };
  return { ...BB_BASE_TOKENS.light, ...BB_BASE_TOKENS.dark, ...root, ...themeBlock(css, ".dark") };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(THEME_CSS, renderThemeCss());
  for (const mode of ["light", "dark"] as const) writeFileSync(CODE_THEME_FILES[mode], renderCodeTheme(mode));
}
