import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { BRAND_PIN, CODE_THEME_FILES, THEME_CSS, VENDORED_THEME, modeTokens, renderThemeCss, stripImport, themeBlock } from "./build.ts";
import { renderCodeTheme, type CodeTheme } from "./code-theme.ts";
import { BB_BASE_TOKENS } from "./bb-base-tokens.ts";
import { contrast, over, resolveColor, toBytes, type Tokens } from "./color.ts";

const vendored = readFileSync(VENDORED_THEME, "utf8");
const MODES = ["light", "dark"] as const;

test("themes/sketchbook.css and both code themes are up to date (npm run build:assets)", () => {
  assert.equal(readFileSync(THEME_CSS, "utf8"), renderThemeCss());
  for (const mode of MODES) assert.equal(readFileSync(CODE_THEME_FILES[mode], "utf8"), renderCodeTheme(mode));
});

test("the theme is under BB's 256 KB cap, inlines Patrick Hand once as the UI font, keeps BB's mono and imports nothing", () => {
  const css = renderThemeCss();
  assert.ok(Buffer.byteLength(css) < 200 * 1024, `${Buffer.byteLength(css)} bytes`);
  assert.equal(css.match(/@font-face \{\n {2}font-family: "Tutor Patrick Hand";\n {2}src: url\("data:font\/woff2;base64,/g)?.length, 1);
  assert.equal(css.match(/@font-face/g)?.length, 1);
  assert.doesNotMatch(css, /@import/);
  assert.doesNotMatch(css, /--font-mono/);
  assert.match(css, /--font-sans: "Tutor Patrick Hand", "Patrick Hand", "Comic Sans MS", /);
  assert.ok(css.startsWith(`/* Generated by app/theme/build.ts from vendor/brand/bb-theme/sketchbook/theme.css (brand ${BRAND_PIN})`));
  assert.match(css.split("\n")[0] ?? "", /Do not edit\. \*\/$/);
});

test("after the fonts, the theme is the vendored brand theme minus its @import, with only the font stack's first family renamed", () => {
  const css = renderThemeCss();
  const fontsEnd = css.lastIndexOf("}\n", css.indexOf(":root,")) + 2;
  const body = css.slice(fontsEnd).replace(/^\n+/, "");
  const expected = stripImport(vendored);
  assert.doesNotMatch(expected, /@import/);
  assert.ok(expected.length > vendored.length - 200, "only the @import went");
  const got = body.split("\n");
  const want = expected.split("\n");
  assert.equal(got.length, want.length);
  const differing = want.map((line, i) => [line, got[i]] as const).filter(([a, b]) => a !== b);
  assert.deepEqual(differing, [
    [
      '  --font-sans: "Patrick Hand", "Comic Sans MS", "Inter Variable", Inter, sans-serif;',
      '  --font-sans: "Tutor Patrick Hand", "Patrick Hand", "Comic Sans MS", "Inter Variable", Inter, sans-serif;',
    ],
  ]);
});

test("the build refuses a brand theme whose font stack no longer starts with Patrick Hand", () => {
  assert.throws(() => renderThemeCss(vendored.replace('--font-sans: "Patrick Hand"', '--font-sans: "Other"')), /Patrick Hand/);
});

test("the contrast model follows BB's cascade: BB light, BB dark, the theme's :root, then its .dark", () => {
  const root = themeBlock(vendored, ":root,\n.light");
  const dark = themeBlock(vendored, ".dark");
  const light = modeTokens(vendored, "light");
  const darkTokens = modeTokens(vendored, "dark");
  // BB derives what the theme leaves unset.
  assert.equal(light["--sidebar-foreground"], BB_BASE_TOKENS.light["--sidebar-foreground"]);
  assert.equal(darkTokens["--sidebar-foreground"], BB_BASE_TOKENS.dark["--sidebar-foreground"]);
  // The theme's :root is injected after BB's .dark with equal specificity, so it wins in dark mode too...
  assert.equal(darkTokens["--muted-foreground"], root["--muted-foreground"]);
  assert.notEqual(darkTokens["--muted-foreground"], BB_BASE_TOKENS.dark["--muted-foreground"]);
  // ...and its .dark wins over its :root.
  assert.equal(darkTokens["--canvas"], dark["--canvas"]);
  // Comments are not declarations.
  assert.equal(root["--pr-merged"], undefined);
});

// Between two near-greys, Chromium's oklch mix loses the hue and renders it as
// 0, so a grey mixed from the warm ink and paper in oklch comes out pink.
const NEUTRAL_ANCHORS = new Set(["--ink", "--canvas", "--sk-ink", "--sk-paper"]);
const oklchInkMix = /color-mix\(in oklch, var\(--ink\) [\d.]+%, var\(--canvas\)\)/;
/** The tokens BB mixes from --ink and --canvas in oklch in `mode`. */
const bbOklchGreys = (mode: (typeof MODES)[number]) =>
  Object.entries(BB_BASE_TOKENS[mode])
    .filter(([, value]) => oklchInkMix.test(value))
    .map(([name]) => name);

test("the theme re-mixes each of BB's oklch greys in that mode's own block, so none keeps BB's pink mix", () => {
  const css = readFileSync(THEME_CSS, "utf8");
  const blocks = { light: themeBlock(css, ":root,\n.light"), dark: themeBlock(css, ".dark") };
  assert.ok(bbOklchGreys("light").includes("--pill-surface-selected"));
  const missing: string[] = [];
  for (const mode of MODES) {
    for (const name of bbOklchGreys(mode)) {
      const value = blocks[mode][name];
      if (value === undefined || value.includes("in oklch")) missing.push(`${mode}: ${name} = ${value ?? "BB's " + BB_BASE_TOKENS[mode][name]}`);
    }
  }
  assert.deepEqual(missing, []);
});

test("the theme mixes no two neutral anchors (--ink, --canvas, --sk-ink, --sk-paper) in oklch", () => {
  const css = readFileSync(THEME_CSS, "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
  const mixes = [...css.matchAll(/color-mix\(in oklch,\s*var\((--[\w-]+)\)[^,]*,\s*var\((--[\w-]+)\)[^)]*\)/g)];
  assert.ok(mixes.length > 0, "the theme still has its oklch mixes with a brand colour");
  const neutral = mixes.filter(([, a, b]) => NEUTRAL_ANCHORS.has(a ?? "") && NEUTRAL_ANCHORS.has(b ?? "")).map(([mix]) => mix);
  assert.deepEqual(neutral, []);
});

test("every grey BB mixes from ink and paper renders warm (red >= green >= blue), in both modes", () => {
  const css = readFileSync(THEME_CSS, "utf8");
  const pink: string[] = [];
  for (const mode of MODES) {
    const tokens = modeTokens(css, mode);
    for (const name of [...bbOklchGreys(mode), "--muted-foreground", "--subtle-foreground", "--readback-foreground"]) {
      // A pill surface is a gradient: check each of its stops.
      const stops = (tokens[name] ?? "").match(/color-mix\([^()]*(?:\([^()]*\)[^()]*)*\)/g) ?? [];
      assert.ok(stops.length > 0, `${mode}: ${name} is a mix`);
      for (const stop of stops) {
        const [r, g, b] = toBytes(resolveColor(stop, tokens)).map(Math.round) as [number, number, number];
        if (!(r >= g && g >= b)) pink.push(`${mode}: ${name} ${stop} renders ${r},${g},${b}`);
      }
    }
  }
  assert.deepEqual(pink, []);
});

const colour = (tokens: Tokens, name: string) => {
  const c = resolveColor(`var(${name})`, tokens);
  return c.alpha < 1 ? over(c, resolveColor("var(--canvas)", tokens)) : c;
};

test("text keeps WCAG AA contrast on the surfaces BB paints it on, in both modes", () => {
  const text: [string, string][] = [
    ["--foreground", "--canvas"],
    ["--foreground", "--sidebar"],
    ["--sidebar-foreground", "--sidebar"],
    ["--foreground", "--surface-selected"],
    ["--muted-foreground", "--canvas"],
    ["--muted-foreground", "--sidebar"],
    // BB uses subtle text at normal size (code comments among it), so it gets the full 4.5:1 too.
    ["--subtle-foreground", "--canvas"],
    ["--subtle-foreground", "--sidebar"],
    ["--readback-foreground", "--canvas"],
    ["--primary-foreground", "--primary"],
    ["--destructive-foreground", "--destructive"],
    ["--destructive-text", "--canvas"],
    ["--warning-text", "--canvas"],
    ["--success", "--canvas"],
    ["--file-accent", "--canvas"],
  ];
  const failures: string[] = [];
  for (const mode of MODES) {
    const tokens = modeTokens(vendored, mode);
    for (const [fg, bg] of text) {
      const ratio = contrast(colour(tokens, fg), colour(tokens, bg));
      if (ratio < 4.5) failures.push(`${mode}: ${fg} on ${bg} is ${ratio.toFixed(2)}:1`);
    }
    // The primary colour is a UI component (buttons, focus), so 3:1.
    const primary = contrast(colour(tokens, "--primary"), colour(tokens, "--canvas"));
    if (primary < 3) failures.push(`${mode}: --primary on --canvas is ${primary.toFixed(2)}:1`);
  }
  assert.deepEqual(failures, []);
});

test("each code theme has its mode's type, sits on that mode's canvas, and keeps every token colour at 4.5:1", () => {
  for (const mode of MODES) {
    const theme = JSON.parse(renderCodeTheme(mode)) as CodeTheme;
    assert.equal(theme.type, mode);
    assert.equal(theme.name, `tutor-sketchbook-${mode}`);
    const background = theme.colors["editor.background"];
    assert.ok(background);
    const canvas = colour(modeTokens(vendored, mode), "--canvas");
    assert.equal(contrast(background, canvas), 1, `${mode}: editor.background is the canvas`);
    const scopes = new Set(theme.tokenColors.flatMap((rule) => rule.scope));
    for (const scope of ["comment", "keyword", "string", "constant.numeric", "entity.name.function", "entity.name.type", "variable", "punctuation", "invalid"]) {
      assert.ok(scopes.has(scope), `${mode}: ${scope}`);
    }
    for (const foreground of [theme.colors["editor.foreground"], ...theme.tokenColors.map((rule) => rule.settings.foreground)]) {
      if (foreground === undefined) continue;
      assert.match(foreground, /^#[0-9a-f]{6}$/);
      const ratio = contrast(foreground, background);
      assert.ok(ratio >= 4.5, `${mode}: ${foreground} on ${background} is ${ratio.toFixed(2)}:1`);
    }
  }
});

test("both code themes share one scope map", () => {
  const scopesOf = (mode: "light" | "dark") => (JSON.parse(renderCodeTheme(mode)) as CodeTheme).tokenColors.map((rule) => rule.scope);
  assert.deepEqual(scopesOf("light"), scopesOf("dark"));
});
