// Generates fonts.css: the @font-face rules with the woff2 files inlined as
// data URLs, because `bb plugin build` has no loader for font files.
// Regenerate after changing a font: npm run fonts
//
// The three Sketchbook families (kit/tokens.json `font`), each a Fontsource
// 5.3.0 Latin 400 file. They are registered as "Tutor …" so they can never
// shadow a font BB or another plugin loads. Code and diffs use BB's
// var(--font-mono), so there is no monospaced face here.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export interface Face {
  family: string;
  file: string;
}

/** Fontsource's `latin` subset (unicode.json and 400.css of each package; the same for all three). */
export const LATIN =
  "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD";

export const FACES: readonly Face[] = [
  { family: "Tutor Luckiest Guy", file: "luckiest-guy-latin-400-normal.woff2" },
  { family: "Tutor Patrick Hand", file: "patrick-hand-latin-400-normal.woff2" },
  { family: "Tutor Patrick Hand SC", file: "patrick-hand-sc-latin-400-normal.woff2" },
];

const DIR = fileURLToPath(new URL(".", import.meta.url));
export const FONTS_CSS = `${DIR}fonts.css`;

/** The inlined @font-face rule for `family` (the theme build reuses it for Patrick Hand). */
export function renderFontFaces(family: string): string {
  const faces = FACES.filter((face) => face.family === family);
  if (faces.length === 0) throw new Error(`no font face for ${JSON.stringify(family)}`);
  return faces
    .map((face) => {
      const data = readFileSync(`${DIR}${face.file}`).toString("base64");
      return [
        "@font-face {",
        `  font-family: "${face.family}";`,
        `  src: url("data:font/woff2;base64,${data}") format("woff2");`,
        "  font-weight: 400;",
        "  font-style: normal;",
        "  font-display: swap;",
        `  unicode-range: ${LATIN};`,
        "}",
      ].join("\n");
    })
    .join("\n");
}

export function renderFontsCss(): string {
  const header = "/* Generated by app/fonts/embed.ts from the .woff2 files beside it. Do not edit. */\n";
  const families = [...new Set(FACES.map((face) => face.family))];
  return header + families.map(renderFontFaces).join("\n") + "\n";
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(FONTS_CSS, renderFontsCss());
}
