// Vendors the brand repo's Sketchbook theme, kit and drawings at a pinned
// commit into vendor/brand/, byte for byte, and checks that they still match.
//
//   node --experimental-strip-types scripts/sync-brand.ts <full sha>   # wipe and rewrite vendor/brand/
//   node --experimental-strip-types scripts/sync-brand.ts --check      # re-fetch at vendor/brand/PIN and compare
//
// The brand repo (lean-software-production/brand) is public, so this fetches
// from raw.githubusercontent.com with no token. Files keep their brand-repo
// paths under vendor/brand/. Two files are made here rather than copied:
// PIN (the full sha) and VOICE.md (the README's "Voice and tone" section).
// --check prints every file that differs, is missing or is extra, and exits 1.
// Behind an HTTP proxy, set NODE_USE_ENV_PROXY=1 so Node's fetch uses it.
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

export const BRAND_REPO = "lean-software-production/brand";
export const VENDOR_DIR = "vendor/brand";

/** Brand-repo paths vendored unchanged. Add a drawing only when a Tutor surface uses it. */
export const MANIFEST: readonly string[] = [
  "bb-theme/sketchbook/theme.css",
  "kit/tokens.json",
  "kit/sketchbook.css",
  "kit/sketchbook.js",
  "kit/icons/checklist.svg",
  "kit/icons/chat.svg",
  "kit/icons/books.svg",
  "kit/icons/robot.svg",
  "kit/characters/waver.svg",
  "kit/characters/explainer.svg",
  "kit/characters/group.svg",
];

const VOICE_HEADING = "## Voice and tone";

/** Fetches a URL's bytes, throwing on anything but success. */
export type Fetcher = (url: string) => Promise<Uint8Array>;

export function rawUrl(sha: string, path: string): string {
  return `https://raw.githubusercontent.com/${BRAND_REPO}/${sha}/${path}`;
}

/** The README's "## Voice and tone" section, heading included, up to the next `## ` heading. */
export function extractVoice(readme: string): string {
  const lines = readme.split("\n");
  const start = lines.findIndex((line) => line.trimEnd() === VOICE_HEADING);
  if (start === -1) throw new Error(`brand README.md has no "${VOICE_HEADING}" heading`);
  const next = lines.findIndex((line, i) => i > start && line.startsWith("## "));
  const section = lines.slice(start, next === -1 ? undefined : next);
  return `${section.join("\n").trimEnd()}\n`;
}

/** Everything vendor/brand/ should hold at `sha`, keyed by path relative to it. */
async function render(sha: string, fetcher: Fetcher): Promise<Map<string, Uint8Array>> {
  const files = new Map<string, Uint8Array>();
  for (const path of MANIFEST) files.set(path, await fetcher(rawUrl(sha, path)));
  const readme = Buffer.from(await fetcher(rawUrl(sha, "README.md"))).toString("utf8");
  const voice =
    `<!-- The brand's voice: README.md's "Voice and tone" section at ${BRAND_REPO}@${sha}.\n` +
    "     Generated by scripts/sync-brand.ts. Do not edit. -->\n\n" +
    extractVoice(readme);
  files.set("VOICE.md", Buffer.from(voice));
  files.set("PIN", Buffer.from(`${sha}\n`));
  return files;
}

function assertFullSha(sha: string): void {
  if (!/^[0-9a-f]{40}$/.test(sha)) throw new Error(`pin a full 40-character commit sha, not ${JSON.stringify(sha)}`);
}

/** Wipes `<root>/vendor/brand/` and rewrites it from the brand repo at `sha`. */
export async function syncBrand(root: string, sha: string, fetcher: Fetcher): Promise<void> {
  assertFullSha(sha);
  const files = await render(sha, fetcher);
  const dir = join(root, VENDOR_DIR);
  await rm(dir, { recursive: true, force: true });
  for (const [path, bytes] of files) {
    await mkdir(dirname(join(dir, path)), { recursive: true });
    await writeFile(join(dir, path), bytes);
  }
}

async function listFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true }).catch(() => []);
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)).split(sep).join("/"));
}

/** Re-fetches at the sha in PIN and returns one line per difference; empty when the tree matches. */
export async function checkBrand(root: string, fetcher: Fetcher): Promise<string[]> {
  const dir = join(root, VENDOR_DIR);
  const pin = await readFile(join(dir, "PIN"), "utf8").catch(() => {
    throw new Error(`${VENDOR_DIR}/PIN is missing; run scripts/sync-brand.ts <sha> first`);
  });
  const sha = pin.trim();
  assertFullSha(sha);
  const expected = await render(sha, fetcher);
  const problems: string[] = [];
  for (const [path, bytes] of expected) {
    const actual = await readFile(join(dir, path)).catch(() => undefined);
    if (actual === undefined) problems.push(`missing: ${VENDOR_DIR}/${path}`);
    else if (!actual.equals(bytes)) problems.push(`differs: ${VENDOR_DIR}/${path}`);
  }
  for (const path of (await listFiles(dir)).sort()) {
    if (!expected.has(path)) problems.push(`extra: ${VENDOR_DIR}/${path}`);
  }
  return problems;
}

/** fetch(), retried once: a flaky fetch should not fail CI. */
export const httpFetcher: Fetcher = async (url) => {
  for (let attempt = 1; ; attempt++) {
    try {
      const response = await fetch(url);
      if (!response.ok) throw new Error(`GET ${url}: ${response.status} ${response.statusText}`);
      return new Uint8Array(await response.arrayBuffer());
    } catch (error) {
      if (attempt >= 2) throw error;
    }
  }
};

async function main(args: string[]): Promise<number> {
  const root = fileURLToPath(new URL("..", import.meta.url));
  if (args.length === 1 && args[0] === "--check") {
    const problems = await checkBrand(root, httpFetcher);
    for (const problem of problems) console.error(problem);
    if (problems.length > 0) {
      console.error(`${VENDOR_DIR} does not match the brand repo at its PIN; re-run scripts/sync-brand.ts <sha>`);
      return 1;
    }
    console.log(`${VENDOR_DIR} matches the brand repo at its PIN`);
    return 0;
  }
  const [sha] = args;
  if (args.length !== 1 || sha === undefined || sha.startsWith("-")) {
    console.error("usage: scripts/sync-brand.ts <full brand sha> | --check");
    return 2;
  }
  await syncBrand(root, sha, httpFetcher);
  console.log(`vendored ${BRAND_REPO}@${sha} into ${VENDOR_DIR}`);
  return 0;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.exitCode = await main(process.argv.slice(2));
}
