// Generates the kit's SVG pieces as TypeScript modules, because `bb plugin
// build` has no loader for .svg files. Regenerate: npm run build:assets
//
// app/sketch/defs.ts: the kit's shared <svg> defs (the three wobble filters
// and the arrowhead marker), read out of vendor/brand/kit/sketchbook.js and
// renamed to tutor-sk-*, matching the url(#tutor-sk-…) references that
// app/sketch/build-kit.ts writes into kit.css. WobbleDefs mounts it.
//
// app/sketch/drawings.ts: each vendored drawing as a base64 data URL. Base64
// keeps the file's bytes exactly as the brand drew them.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ID_PREFIX } from "./build-kit.ts";

const path = (relative: string) => fileURLToPath(new URL(relative, import.meta.url));

export const VENDORED_JS = path("../../vendor/brand/kit/sketchbook.js");
export const DEFS_TS = path("./defs.ts");
export const DRAWINGS_TS = path("./drawings.ts");
const BRAND_PIN = () => readFileSync(path("../../vendor/brand/PIN"), "utf8").trim();

/** The vendored drawings (scripts/sync-brand.ts), by kind. */
export const ICONS = ["books", "chat", "checklist", "robot"] as const;
export const CHARACTERS = ["explainer", "group", "waver"] as const;

export function drawingPath(kind: "icons" | "characters", name: string): string {
  return path(`../../vendor/brand/kit/${kind}/${name}.svg`);
}

/** The markup the kit script injects: its `var defs = "…"` string literal, unescaped. */
export function extractDefs(js: string): string {
  const match = /\bvar defs = ("(?:[^"\\]|\\.)*");/.exec(js);
  if (!match) throw new Error("the kit script has no `var defs = \"…\";` to read");
  return JSON.parse(match[1]!) as string;
}

/** Every kit id, and every reference to one, moves to the tutor-sk-* names. */
export function renameDefs(html: string): string {
  return html.replace(/\bid="sk-/g, `id="${ID_PREFIX}`).replace(/url\(#sk-/g, `url(#${ID_PREFIX}`);
}

export function renderDefsModule(js: string = readFileSync(VENDORED_JS, "utf8")): string {
  const html = renameDefs(extractDefs(js));
  const id = /^<svg id="([^"]+)"/.exec(html)?.[1];
  if (!id) throw new Error("the kit defs do not start with an <svg id=…>");
  return [
    `// Generated by app/sketch/build-assets.ts from vendor/brand/kit/sketchbook.js (brand ${BRAND_PIN()}). Do not edit.`,
    `export const DEFS_ID = ${JSON.stringify(id)};`,
    `export const DEFS_HTML = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
}

function dataUrl(kind: "icons" | "characters", name: string): string {
  return `data:image/svg+xml;base64,${readFileSync(drawingPath(kind, name)).toString("base64")}`;
}

export function renderDrawingsModule(): string {
  const map = (kind: "icons" | "characters", names: readonly string[]) =>
    names.map((name) => `  ${name}: ${JSON.stringify(dataUrl(kind, name))},`).join("\n");
  return [
    `// Generated by app/sketch/build-assets.ts from vendor/brand/kit/{icons,characters} (brand ${BRAND_PIN()}). Do not edit.`,
    "export const icons = {",
    map("icons", ICONS),
    "} as const;",
    "export const characters = {",
    map("characters", CHARACTERS),
    "} as const;",
    "export type IconName = keyof typeof icons;",
    "export type CharacterName = keyof typeof characters;",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(DEFS_TS, renderDefsModule());
  writeFileSync(DRAWINGS_TS, renderDrawingsModule());
}
